# Generated by Django 5.0.4 on 2024-04-11 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PublishInfo', to='recipes.publisher'),
        ),
    ]
