# Generated by Django 5.0.4 on 2024-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_link',
            field=models.CharField(default='Assets/defaultImage.png', max_length=1000),
        ),
    ]
